version: "3"

services:
  support:
    image: postgres:14.7-alpine
    container_name: db_postgres
    env_file: ".env"
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

      
volumes:
  pg_data: {}