version: "3"

services:
  postgres:
    image: postgres:14
    container_name: support_db
    env_file: ".env"
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data


  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    command: "gunicorn src.config.wsgi -c gunicorn_config.py"
    image: support_backend
    container_name: support_app
    env_file: ".env"
    depends_on:
      - "postgres"
    volumes:
      - ".:/app/"
    ports:
      - "8000:8000"
  
  
  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/usr/share/nginx/html/static
    depends_on:
      - app


volumes:
  pg_data:
  staticfiles: