# Generated by Django 4.1.4 on 2022-12-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="email_address",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=35, null=True, verbose_name="first_name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=35, verbose_name="last_name"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
