# Generated by Django 4.1.6 on 2023-02-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_rename_heder_ticket_header"),
        ("comments", "0002_alter_comment_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="prev_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next",
                to="comments.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tickets.ticket",
            ),
        ),
    ]
